version: '3.8'

services:
  lec-chatbot:
    image: narutosimaha/lec-chatbot
    command:  ["python","-m", "debugpy", "--log-to", "/usr/local/src/lec-chatbot/logs" ,"--listen", "0.0.0.0:5678", "--wait-for-client", "main.py"]
    # command: ["python", "main.py", "-d"]
    environment: 
      - MODEL_NAME=small
      - BOT_PASSWORD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc4NzIxMTYsImlhdCI6MTY3Nzg2NzMxNywiaWQiOiJjaGF0Ym90In0.oBO_gjkDcjot2A9guG05_ku51H45l9D8IKPHRs3daWc
      - BOT_JID=chatbot@localhost
      - LANGEX_XMPP_HOSTNAME=lec-chatserver
      - LANGEX_XMPP_PORT=5222
      - APP_BROKERS=kafka:9092
      - LANGEX_CHATDB_STRING=postgresql://langteam:Aa1234@langchat-db:5432/langchat
      - PLATFORM=DOCKER
      - FILE_SERVICE=lec-chatgw
      - MODE=development
    volumes:
      - model:/app/chatbot/models/whisper/model
      - model_cache:/.cache/huggingface
      - ./logs:/app/lec-chatbot/logs
    networks:
      - vutl
    ports:
      - "5678:5678"
networks:
  vutl:
    external: True

volumes:
  model:
  model_cache:

